/* Catálogos de la plataforma de solicitudes de movimientos (los mismos de la versión probada).
   Generado desde solicitudes-movimientos/Code.gs del repositorio privado; para cambiar un catálogo edítalo aquí. */
export const AREAS = ["Customer Service","Mercadotecnia","Calidad","Distribución","Almacén / CEDIS","Logística","Producción"];
/* Tipo de movimiento (qué se hace con el producto). Las claves se conservan para no afectar solicitudes ya guardadas. */
export const TIPOS = [["envio","Entrega de producto","Llevar producto o material a un destino."],["entrega_recoleccion","Entrega y posterior recolección","Se entrega y después se recoge (eventos, stands, sillas, mobiliario)."],["recoleccion","Recolección","Recoger material en un punto."],["devolucion","Devolución de producto","Material que regresa un cliente. Pide fotos y checklist."],["traslado","Traslado","Entre plantas, CEDIS, bodegas o sucursales."],["mercadotecnia","Mercadotecnia","Stands, exhibidores y eventos."],["otro","Otro","Cualquier otro movimiento; lo especificas."]];
/* Movimientos en los que se pregunta si el material regresa después (fecha de recolección). */
export const CON_RECOLECCION = ["envio","mercadotecnia","otro"];
/* Tipo de producto (qué se mueve). Los reutilizables sugieren recolección; los demás, «No requiere recolección». */
export const PRODUCTOS = [["Mobiliario","Mesas, vitrinas, exhibidores."],["Estructuras de metal","Racks, bases y estructuras."],["Stand completo","Stand para evento o exposición."],["Sillas",""],["Regalos","Artículos promocionales."],["Vinos",""],["Otro","Lo especificas."]];
export const REUTILIZABLES = ["Mobiliario","Estructuras de metal","Stand completo","Sillas"];
/* Tipo de solicitud. Las solicitudes antiguas guardadas como «Normal» se muestran como «Programado». */
export const PRIORIDADES = ["Programado","Urgente"];
export const COSTOS = ["Departamento solicitante","Otro departamento","Cliente","Proveedor","Evento / Proyecto","Otro"];
export const AUT_ESTADOS = ["Pendiente de autorización","Autorizado","Rechazado"];
export const AUT_PENDIENTE = "Pendiente de autorización";
/* Días mínimos de anticipación: con menos, la solicitud es urgente y requiere autorización del Gerente de Área. */
export const DIAS_ANTICIPACION = 2;
export const ESTADOS = {"recibida":"Recibida","en_revision":"En revisión","informacion":"Falta información","programada":"Programada","en_transito":"En tránsito","completada":"Completada","cancelada":"Cancelada","rechazada":"No procede"};
export const ABIERTOS = ["recibida","en_revision","informacion","programada","en_transito"];
export const CANCELABLES = ["recibida","en_revision","informacion"];
export const FORMAS_ENVIO = ["Camión / unidad","Paquetería"];
export const PAQUETERIA = "Paquetería";
export const FACTOR_VOLUMETRICO = 5000;
export const MOTIVOS_DEVOLUCION = ["Cambio de tono","Cambio de calibre","Cambio de formato","Producto dañado","Producto equivocado","Producto incompleto","Sobrante de obra","El cliente ya no lo requiere","Otro"];
export const CHECKLIST_DEVOLUCION = ["Está en su empaque original y las cajas están cerradas","Las cajas no tienen golpes ni humedad, y no hay piezas rotas o despostilladas","No ha sido instalado, cortado ni manipulado","Las etiquetas (lote, tono y calibre) se ven y coinciden con lo facturado","La cantidad coincide con la factura o la nota de crédito","Está en tarima, flejado y emplayado, listo para cargar","La devolución está autorizada (nota de crédito o autorización del gerente)"];
export const CATEGORIAS = ["EXTERNO","ALMACEN","OBRA","PAQUETERIA","OTROS"];
export const TRANSPORTISTAS = ["ACARREOS MAMAEV","ALMEX","AM INTERMODAL","AUTOEXPRESS AGUILAR","AUTOEXPRESS CARRASCO","AUTOEXPRESS CERVANTES","AUTOEXPRESS DEL MINERAL","AUTOEXPRESS ESTRADA","AUTOEXPRESS MEDINA","AUTOEXPRESS MUÑOZ","AUTOEXPRESS OLIVAS","AUTOEXPRESS PARGA","AUTOEXPRESS POTRILLOS","AUTOEXPRESS VELAZQUEZ","AUTOTRANSPORTES HERIVA","CH ROBINSON","CLIENTE ENVIA UNIDAD","DANIEL FERNANDEZ","DESARROLLO LOGISTICO","FEMA","FRANCISCO ORTEGA","GROMAR","JOEL MARTINEZ","LOGISTICA INTERNACIONAL","MASER","MATA TRUCKING","OSVALDO ORTIZ","OVERSEAS","PALOS GARZA","PAQUETEEXPRESS","PAQUETERIA","ROJAS","SOLISTICA","TARKUS TRANSPORTES","TRANSPORTE BISONTE","TRANSPORTES 3H","TRANSPORTES ACUÑA","TRANSPORTES ARANCETION","TRANSPORTES AURORA ESQUIVEL","TRANSPORTES CARMONA","TRANSPORTES CARVAN","TRANSPORTES DOMINGUEZ","TRANSPORTES ELEAM","TRANSPORTES GUTIERREZ","TRANSPORTES HEFL","TRANSPORTES J HERNANDEZ","TRANSPORTES JASA","TRANSPORTES LEXA","TRANSPORTES LINARES","TRANSPORTES LOPEZ INTERNACIONAL","TRANSPORTES LOZAGUI","TRANSPORTES MAROLOS","TRANSPORTES MARTINEZ GUTIERREZ","TRANSPORTES NAVARRO","TRANSPORTES PINEDO","TRANSPORTES SALAS","TRANSPORTES SIFUENTES","TRANSPORTES TEEXSA","TRANSPORTES TNT","TRANSPORTES TORRES","TRANSPORTES TRAZA","TRANSPORTES TREJOS TRUCKING","TRANSPORTES VATRU","TRUCKA","UBER FREIGHT"];
export const TIPOS_UNIDAD = ["SENCILLO","TORTON","RABON","CAMIONETA 3.5","CAJA SECA 53","CAJA SECA 48","CAJA CERRADA","FULL","PLATAFORMA SENCILLO","PLATAFORMA FULL","CONTENEDOR 20","PAQUETERIA"];
/* Campos que captura quien solicita: [clave, etiqueta, obligatorio, máximo].
   Por compatibilidad con las solicitudes ya guardadas, algunos conservan su nombre interno:
   area = Departamento solicitante, motivo = Descripción de la solicitud, referencia = Folio, cliente = Factura,
   horario = Requiere cita («Sí» o vacío). Los artículos, paquetes y la autorización se validan aparte. */
export const CAMPOS = [["solicitante","Nombre",true,120],["area","Departamento solicitante",true,80],["correo","Correo",true,160],["telefono","Teléfono o extensión",true,40],["producto_tipo","Tipo de producto",true,40],["producto_otro","Especificar tipo de producto",false,120],["tipo","Tipo de movimiento",true,30],["tipo_otro","Especificar movimiento",false,120],["prioridad","Tipo de solicitud",true,12],["forma_envio","Forma de envío",true,30],["referencia","Folio",false,120],["cliente","Factura",false,160],["horario","Requiere cita",false,4],["motivo","Descripción de la solicitud",true,5000],["observaciones","Observaciones",false,2000],["dev_motivo","Motivo de la devolución",false,60],["dev_checklist","Puntos que cumple el material",false,1500],["costo_absorbe","¿Quién absorbe el costo?",true,40],["costo_detalle","Detalle de quién absorbe el costo",false,120],["fecha_requerida","Fecha requerida",false,10],["fecha_abierta","Fecha abierta",false,4],["recoleccion","Recolección",false,4],["fecha_recoleccion","Fecha de recolección",false,10],["recoleccion_abierta","Fecha de recolección abierta",false,4],["aut_gerente","Gerente de Área que autoriza",false,120],["origen_nombre","Lugar de salida",true,160],["origen_direccion","Dirección de salida",true,240],["origen_ciudad","Ciudad de salida",true,120],["origen_contacto","Contacto en salida",false,160],["origen_telefono","Teléfono en salida",false,40],["origen_referencias","Referencias de salida",false,300],["destino_nombre","Lugar de entrega",true,160],["destino_direccion","Dirección de entrega",true,240],["destino_ciudad","Ciudad de entrega",true,120],["destino_contacto","Contacto en entrega",false,160],["destino_telefono","Teléfono en entrega",false,40],["destino_referencias","Referencias de entrega",false,300]];
export const CAMPOS_LOGISTICA = ["folio_cstext","categorizacion","responsable","transportista","unidad_asignada","guia","fecha_programada","notas_internas"];
